p4 set P4IGNORE=.p4ignore
attrib -r Plugins/*.* /s
attrib -r Binaries/*.* /s
attrib -r Plugins /s
attrib -r Binaries /s
attrib -r *.sln /s
p4 reconcile
p4 reconcile Binaries/...
p4 reconcile Config/...
p4 reconcile Content/...
p4 reconcile Plugins/...
p4 reconcile Source/...
p4 reconcile Library/...
p4 reconcile Packages/...
p4 reconcile ProjectSettings/...